// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgkcgxcangzozhculetl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZna2NneGNhbmd6b3poY3VsZXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjU0NTMsImV4cCI6MjA2MTM0MTQ1M30.cTE_FiQiJcoBxyed2DhyTT0t8q0-_kAUtk25zMDP_dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);